title: BikeGuider
description: A navigation and safety system for bikers that uses handlebar-mounted vibration motors and computer vision to enhance situational awareness.
theme: just-the-docs
url: https://simonw412.github.io/BikeGuider/